baseURL = 'https://www.idsilab.org/'
title = 'H-CORD Lab'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false
disableKinds = ['taxonomy', 'term']

[params]
  labNameZh = '人本机器人与智能设计实验室'
  labNameEn = 'Human-Centered Robotics and Design Laboratory'
  abbreviation = 'H-CORD Lab'
  descriptionZh = '人本机器人与智能设计'
  descriptionEn = 'Human-Centered Robotics and Design'
  email = 'xymao@njust.edu.cn'
  location = 'China'

[languages]
  [languages.zh]
    languageCode = 'zh-CN'
    languageName = '中文'
    weight = 1
    title = 'H-CORD Lab'
    [languages.zh.params]
      labNameZh = '人本机器人与智能设计实验室'
      labNameEn = 'Human-Centered Robotics and Design Laboratory'
      abbreviation = 'H-CORD Lab'
      descriptionZh = '人本机器人与智能设计'
      descriptionEn = 'Human-Centered Robotics and Design'
      email = 'xymao@njust.edu.cn'
      location = 'China'
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 2
    title = 'H-CORD Lab'
    [languages.en.params]
      labNameZh = '人本机器人与智能设计实验室'
      labNameEn = 'Human-Centered Robotics and Design Laboratory'
      abbreviation = 'H-CORD Lab'
      descriptionZh = '人本机器人与智能设计'
      descriptionEn = 'Human-Centered Robotics and Design'
      email = 'xymao@njust.edu.cn'
      location = 'China'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
